name: BeastWithdraw
authors: [MrAxeTv]
main: me.mraxetv.beastwithdraw.MyPlugin
description: Simple handy withdraw plugin.
version: ${project.version}
softdepend: [Essentials, Vault, BeastTokens,BeastCore]
api-version: 1.13
website: www.BeastUniverseStudio.com
commands:
  Xpbottle:
    usage: /<command>
    aliases: []
    description: Xp withdraw command.
  Beastwithdraw:
    usage: /<command>
    aliases: []
    description: Info command.
  bWithdraw:
    usage: /<command>
    description: Withdraw Money.
  btWithdraw:
    usage: /<command>
    description: Withdraw Money.
