name: BeastWithdraw
authors: [MrAxeTv]
main: me.mraxetv.beastwithdraw.BeastWithdrawPlugin
description: Simple handy withdraw plugin.
version: ${project.version}
softdepend: [Essentials, Vault, BeastTokens]
depend: [BeastLib]
api-version: 1.13
website: www.BeastUniverseStudio.com